const elements = {
    yesBtn: document.getElementById('yes-btn'),
    noBtn: document.getElementById('no-btn'),
    yesArrow: document.getElementById('yes-arrow'),
    successArrow: document.getElementById('success-arrow'),
    mainCard: document.getElementById('main-card'),
    successCard: document.getElementById('success-card'),
    successCelebration: document.getElementById('celebration'),
    heartsContainer: document.getElementById('hearts-container'),
    cherryBlossoms: document.getElementById('cherry-blossoms'),
    nervousCat: document.querySelector('.nervous-cat'),
    darkmodeToggle: document.getElementById('darkmode-toggle'),
    chooseLocationBtn: document.getElementById('choose-location-btn'),
    locationCard: document.getElementById('location-card'),
    selectedLocationMessage: document.getElementById('selected-location-message'),
    locationCelebration: document.getElementById('location-celebration'),
    confirmLocationBtn: document.getElementById('confirm-location-btn'),
    datetimeCard: document.getElementById('datetime-card'),
    confirmDatetimeBtn: document.getElementById('confirm-datetime'),
    addDatetimeBtn: document.getElementById('add-datetime'),
    datetimeRowTemplate: document.getElementById('datetime-row-template'),
    datetimeContainer: document.querySelector('.datetime-container'),
    selectedDatetimeMessage: document.getElementById('selected-datetime-message'),
    foodNextBtn: document.getElementById('food-next-btn'),
    foodCard: document.getElementById('food-card'),
    selectedFoodMessage: document.getElementById('selected-food-message'),
    foodCelebration: document.getElementById('food-celebration'),
    confirmFoodBtn: document.getElementById('confirm-food-btn'),
    finalMessage: document.getElementById('final-message'),
    drinksNextBtn: document.getElementById('drinks-next-btn'),
    drinksCard: document.getElementById('drinks-card'),
    selectedDrinkMessage: document.getElementById('selected-drink-message'),
    drinksCelebration: document.getElementById('drinks-celebration'),
    confirmDrinkBtn: document.getElementById('confirm-drink-btn'),
    finalDrinkMessage: document.getElementById('final-drink-message'),
    completionNextBtn: document.getElementById('completion-next-btn'),
    noteCard: document.getElementById('note-card'),
    noteTextarea: document.getElementById('note-textarea'),
    noteWordCounter: document.querySelector('#note-card .word-counter'),
    saveNoteBtn: document.getElementById('save-note-btn'),
    completionCard: document.getElementById('completion-card'),
    completionHearts: document.getElementById('completion-hearts'),
    emailForm: document.getElementById('email-form'),
    userEmailInput: document.getElementById('user-email'),
    sendEmailBtn: document.getElementById('send-email-btn'),
    emailError: document.getElementById('email-error'),
    emailSuccess: document.getElementById('email-success'),
    noteCelebration: document.getElementById('note-celebration'),
    datetimeCelebration: document.getElementById('datetime-celebration'),
    foodSelectionStatus: document.getElementById('food-selection-status'),
    drinkSelectionStatus: document.getElementById('drink-selection-status'),
    bgMusic: document.getElementById('bg-music'),
    musicWidget: document.getElementById('music-widget'),
    musicToggle: document.getElementById('music-toggle'),
    musicPanel: document.getElementById('music-panel'),
    musicPlayToggle: document.getElementById('music-play-toggle'),
    musicVolumeDown: document.getElementById('music-volume-down'),
    musicVolumeUp: document.getElementById('music-volume-up'),
    musicVolumeValue: document.getElementById('music-volume-value')
};

const tileButtons = () => document.querySelectorAll('.tile-btn');
const customButtons = () => document.querySelectorAll('.custom-btn');

export { elements, tileButtons, customButtons };
